### ISSUE TITLE
Video playback of MP4 files does not work.

### ISSUE THREAD

**Issue by mcmdev** [TheJoCraftNET/MapEngine-MediaExtension#1]
As this extension documented yet, I just tried to throw a MP4 video at it and came across an Exception that should probably not be thrown. Unless I'm doing something very wrong, this should be easily reproducible.

`
[01:05:55 WARN]: Exception in thread "pool-12-thread-1" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 303232 out of bounds for int[296640]
[01:05:55 WARN]: 	at java.base/java.lang.System.arraycopy(Native Method)
[01:05:55 WARN]: 	at MapEngine-MediaExt-1.0.5-all.jar//de.pianoman911.mapengine.media.converter.MapEngineConverter.convert(MapEngineConverter.java:35)
[01:05:55 WARN]: 	at MapEngine-MediaExt-1.0.5-all.jar//de.pianoman911.mapengine.media.movingimages.FFmpegFrameSource.next(FFmpegFrameSource.java:56)
[01:05:55 WARN]: 	at MapEngine-MediaExt-1.0.5-all.jar//de.pianoman911.mapengine.media.movingimages.MovingImagePlayer.lambda$new$0(MovingImagePlayer.java:30)
[01:05:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:05:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:05:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
`

This is the piece of code used to load the video file.
`
    @Override
    public void initialize(IDrawingSpace drawingSpace) {
        File file = new File(this.file);
        if(!file.exists())  {
            throw new IllegalStateException("Video file " + file.getAbsolutePath() + " does not exist.");
        }

        this.frameSource = new FFmpegFrameSource(file, 10, drawingSpace, true);
        this.frameSource.start();
    }
`

**Comment by booky10** [comment]
In which format is the video encoded?
I've just tried this with basically the same code and it did work for me.
